### ISSUE TITLE
XFileInputStream.read fails with java.lang.NegativeArraySizeException: when size of NFS file > 2.5 GB

### ISSUE THREAD

**Issue by vikasmadhusudana** [raisercostin/yanfs#6]
Steps to reproduce:
+++++++++++++++
Have a 3.5 GB file in NFS share 

Use below snippet to read from NFS share

```

   import com.sun.xfile.*;                                                         
   import org.apache.commons.io.*;                                                 
  import java.io.*;                                                               
                                               
  class NFSCopyTest {                                                             
                                                                                
  public static void main(String[] args) {                                      
    try {                                                                       
      XFile xfile = new XFile(args[0]);                                         
      XFileInputStream inputStream = new XFileInputStream(xfile);               
                                                                                
      System.out.println("CanRead: " + xfile.canRead());                        
      System.out.println("Length: " + xfile.length());                          
      byte[] arr = new byte[1024];                                              
      inputStream.read(arr);                                                    
      }catch(Exception e) {                                                       
      e.printStackTrace();                                                      
      System.out.println(e);                                                    
      }                                                                           
     }                                                                             
  }                   
```

It fails with below error

CanRead: true
Length: 3809694132
java.lang.NegativeArraySizeException: -14808
	at com.sun.nfs.Nfs.read(Nfs.java:254)
	at com.sun.nfs.XFileAccessor.read(XFileAccessor.java:334)
	at com.sun.xfile.XFileInputStream.XFAread(XFileInputStream.java:107)
	at com.sun.xfile.XFileInputStream.read(XFileInputStream.java:144)
	at NFSCopyTest.main(NFSCopyTest.java:18)
java.lang.NegativeArraySizeException: -14808

It appears that long to int conversion in line 254 of NFs.java is causing the number  to be negative 

bufferList = new Buffer[(int) length() / rsize + 1];

**Comment by raisercostin** [comment]
Fixed by your merge request in #7
